output_dir: /home/icb/yue.hu/proj_genefun/NBFNet/experiments/

dataset:
  class: biomedical
  path: /lustre/groups/crna01/datasets/linkpred/PC_KEGG_nofact/
  include_factgraph: no
  


task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: DistMult
    embedding_dim: 512
    l3_regularization: 1.0e-4
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 1
  sample_weight: yes

optimizer:
  class: Adam
  lr: 1.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 1024

train:
  num_epoch: 500

metric: mrr
