output_dir: /home/icb/yue.hu/proj_genefun/NBFNet/experiments/

dataset:
  class: biomedical
  path: /lustre/groups/crna01/datasets/linkpred/PC_KEGG_0602/
  include_factgraph: yes
  fact_as_train: yes
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: RotatE
    embedding_dim: 128
    max_score: 6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 1
  sample_weight: yes

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 4096

train:
  num_epoch: 100

metric: mrr
