output_dir: /lustre/groups/crna01/projects/genefunction/experiments/

dataset:
  class: biomedical
  path: /home/icb/yue.hu/proj_genefun/NBFNet/data/PC_KEGG_0602
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  conditional_probability: yes
  full_batch_eval: yes


optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 8
  

train:
  num_epoch: 8
  #batch_per_epoch: 1000
  
metric: mrr
