output_dir: /lustre/groups/crna01/projects/genefunction/NBFNet/experiments

dataset:
  class: biomedical
  path: /lustre/groups/crna01/datasets/primekg/disease_split/cardiovascular_42/
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: {{hidden_layers}} 
    message_func: distmult
    aggregate_func: {{agg_fun}}
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: yes
  criterion: bce
  num_negative: {{neg_samp}}
  strict_negative: yes
  adversarial_temperature: {{adv_tmp}}
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  gene_annotation_predict: no
  conditional_probability: {{cond_prob}}
  full_batch_eval: True




optimizer:
  class: Adam
  lr: {{lr}}

engine:
  gpus: {{ gpus }}
  batch_size: 8
  

train:
  num_epoch: {{epochs}}
  batch_per_epoch: 1000
  
metric: mrr
