output_dir: /network/scratch/s/sophie.xhonneux/NBFNet/experiments/

dataset:
  class: biomedical
  path: /home/mila/s/sophie.xhonneux/projects/NBFNet/NBFNet/data/mock
  include_factgraph: True
  
task:
  class: KnowledgeGraphCompletionBiomed
  # class: KnowledgeGraphEmbeddingEx
  model:
    class: NodeEncoder
    gnn_model:
      class: BatchedRGCN
      input_dim: 128
      hidden_dims: [128, 128]
      layer_norm: yes
      short_cut: yes
      batch_norm: yes
    score_model:
      class: RotatEScore
      embedding_dim: 128
      max_score: 9
    flip_edge: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  # evaluation_target: both
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  conditional_probability: yes
  full_batch_eval: False




optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  

train:
  num_epoch: 5
  #batch_per_epoch: 10
  
metric: mrr

